blank_issues_enabled: true
contact_links:
  - name: ğŸ§‘â€ğŸ¤â€ğŸ§‘ Community Discord
    url: https://discord.gg/6UyHPeGZAC
    about: Interact with the Saal.ai community here by asking for help, discussing and more!
