blank_issues_enabled: true
contact_links:
  - name: ğŸ§‘â€ğŸ¤â€ğŸ§‘ Community Discord
    url: https://discord.gg/6UyHPeGZAC
    about: Interact with the Mintplex Labs community here by asking for help, discussing and more!
  - name: ğŸ“§ E-mail the team
    url: "mailto:team@mintplexlabs.com"
    about: Contact the core-team about a question.
